# Generated by Django 5.2.3 on 2025-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_finance_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='finance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finance',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Wallet')], default='cash', max_length=30),
        ),
    ]
