# Generated by Django 5.2.3 on 2025-08-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_finance_category_finance_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='payment_method',
            new_name='payment_type',
        ),
    ]
